name: Build and Create Release Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
    
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
        
      - name: Install ambuild2
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Checking out MM:Source
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: metamod-source

      - name: Checking out hl2sdk
        uses: actions/checkout@v4
        with:
          repository: 'alliedmodders/hl2sdk'
          ref: 'e6dc3f8a409a487728ffa0fe0ff901cbfd683b9f'
          path: 'hl2sdk-cs2'
      
      - name: Create build directory
        run: |
          mkdir build

      - name: Compiling files
        working-directory: build
        run: |
          python3 ../configure.py --hl2sdk-root "../" --gen=vs --vs-version 17
          MSBuild cs2desubtick.vcxproj /p:Configuration=Default /p:Platform=x64 /p:Optimization=2

      - name: Make package
        working-directory: build
        run: |
          COPY cs2desubtick.vdf addons/metamod/
          COPY "cs2desubtick - Default/cs2desubtick.dll" addons/cs2desubtick/bin/win64/
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: desubtick
          path: |
                build
                !.vs
                !"cs2desubtick -Default"
                !cs2desubtick.vcxproj
                !.github
                !.git
                !.gitattributes
                !.cache
                !pdblog.txt
